### ISSUE TITLE
Meteor v 0.9.4 and 1.0 Issue

### ISSUE THREAD

**Issue by nspangler** [pahans/reactive-modal#17]
I have noticed that the z-index on the modal isn't functioning correctly after upgrading my packages and meteor. I am using mizzao:bootstrap-3, this reactive-modal package and the latest version of meteor. See image below. When I run `meteor --release 0.9.3' everything works fine. However when I try upgrading everything fails. I have tried to explicitly set the z-index of the modal from the default 1050 to a different value however that doesn't seem to be doing anything. Any thoughts?  
![screen shot 2014-11-03 at 8 33 56 am](https://cloud.githubusercontent.com/assets/5549886/4884768/f5c36ff6-636e-11e4-823f-cb94f09c6b64.png)

**Comment by lionelromanelli** [comment]
I had same problem. I replaced mizzao:bootstrap-3 by foldor:bootstrap-3 and it works!
